CREATE TABLE TB_ADDRESS (
  ADDRESS_ID BIGINT NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  NUMBER INTEGER NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  CEP VARCHAR(255) NOT NULL,
  CREATE_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  PRIMARY KEY (ADDRESS_ID)
);

CREATE TABLE TB_CANCEL (
  CANCEL_ID BIGINT NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  CANCEL_REQUESTED_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CANCEL_CONFIRMED_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  PRIMARY KEY (CANCEL_ID)
);

CREATE TABLE TB_LOCAL (
  LOCAL_ID BIGINT NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  ADDRESS_ID BIGINT NOT NULL,
  CREATE_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  FOREIGN KEY(ADDRESS_ID) REFERENCES TB_ADDRESS (ADDRESS_ID),
  PRIMARY KEY (LOCAL_ID)
);

CREATE TABLE TB_COURT (
  COURT_ID BIGINT NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  TYPE VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  CREATE_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  LOCAL_ID BIGINT NOT NULL,
  FOREIGN KEY (LOCAL_ID) REFERENCES TB_LOCAL (LOCAL_ID),
  PRIMARY KEY (COURT_ID)
);

CREATE TABLE TB_SCHEDULER (
  SCHEDULER_ID BIGINT NOT NULL,
  CUSTOMER_ID VARCHAR(255) NOT NULL,
  STATUS VARCHAR(255) NOT NULL,
  COURT_ID BIGINT NOT NULL,
  CANCEL_ID BIGINT,
  SCHEDULE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONFIRM_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CREATE_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  FOREIGN KEY (CANCEL_ID) REFERENCES TB_CANCEL (CANCEL_ID),
  FOREIGN KEY (COURT_ID) REFERENCES TB_COURT (COURT_ID),
  PRIMARY KEY (SCHEDULER_ID)
);

CREATE SEQUENCE ADDRESS_ID_SEQ START WITH 1;
CREATE SEQUENCE CANCEL_ID_SEQ START WITH 1;
CREATE SEQUENCE LOCAL_ID_SEQ START WITH 1;
CREATE SEQUENCE COURT_ID_SEQ START WITH 1;
CREATE SEQUENCE SCHEDULER_ID_SEQ START WITH 1;
